services:
    app.token_authenticator:
        class: ApiBundle\Security\TokenAuthenticator
        arguments: ['@doctrine.orm.entity_manager', '@router']
#    api.example:
#        class: ApiBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
