<?php

namespace ApiBundle\Repository;

/**
 * ShopUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopUserRepository extends \Doctrine\ORM\EntityRepository
{
}
